Repository urbanopt/urbanopt.github.io, pull requests merged in 2020-03, with the labels that each got.

#35 Remove blank lines that broke template operation
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: bug

#46 temporarily replace building type names on example project drawing
  doc_files/building_types_ISO.jpg
Labels: March Release

#48 Remove issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: March Release

#47 March release
  README.md
  developer_resources/compatibility_matrix.md
  overview/definitions.md
  overview/structure.md
  usage/example.md
  usage/run_project.md
Labels: March Release

#60 Reopt cli
  usage/run_project.md
Labels: March Release, documentation
